export const spec = {
  $schema: 'https://ilo-lang.ai/spec.schema.json',
  language: 'ilo',
  version: '0.1',
  description:
    'Token-optimised programming language for AI agents. Prefix notation, strongly typed, verified before execution.',
  homepage: 'https://ilo-lang.ai',
  repository: 'https://github.com/ilo-lang/ilo',
  spec: 'https://github.com/ilo-lang/ilo/blob/main/SPEC.md',
  syntax: {
    notation: 'prefix',
    function_definition: 'name params:types>return;body',
    function_call: 'name args',
    statement_separator: ';',
    comment: '--',
    auto_unwrap_suffix: '!',
  },
  types: {
    n: { name: 'number', notes: 'Integer or float (NaN-boxed at runtime)' },
    t: { name: 'text', notes: 'UTF-8 string' },
    b: { name: 'boolean' },
    L: { name: 'list', notes: 'Use as `L _` where `_` is element type' },
    M: { name: 'map', notes: 'Use as `M k v`' },
    R: { name: 'result', notes: 'Use as `R ok err`. Auto-unwrap with `!`' },
    fn: { name: 'function', notes: 'Function value, can be passed and returned' },
    _: { name: 'wildcard', notes: 'Generic placeholder' },
  },
  operators: {
    arithmetic: [
      { sym: '+', sig: 'n n > n', desc: 'add' },
      { sym: '-', sig: 'n n > n', desc: 'subtract' },
      { sym: '*', sig: 'n n > n', desc: 'multiply' },
      { sym: '/', sig: 'n n > n', desc: 'divide' },
      { sym: '%', sig: 'n n > n', desc: 'modulo' },
    ],
    comparison: [
      { sym: '==', sig: '_ _ > b', desc: 'equal' },
      { sym: '!=', sig: '_ _ > b', desc: 'not equal' },
      { sym: '>', sig: 'n n > b', desc: 'greater than' },
      { sym: '<', sig: 'n n > b', desc: 'less than' },
      { sym: '>=', sig: 'n n > b', desc: 'greater or equal' },
      { sym: '<=', sig: 'n n > b', desc: 'less or equal' },
    ],
    logic: [
      { sym: '&', sig: 'b b > b', desc: 'logical and' },
      { sym: '|', sig: 'b b > b', desc: 'logical or' },
      { sym: '!', sig: 'b > b', desc: 'logical not' },
    ],
  },
  builtins: {
    text: [
      { name: 'cat', alias: 'concat', sig: 't t > t', desc: 'concatenate two strings' },
      { name: 'len', alias: 'length', sig: 't > n', desc: 'string length' },
      { name: 'trm', alias: 'trim', sig: 't > t', desc: 'trim whitespace' },
      { name: 'spl', alias: 'split', sig: 't t > L t', desc: 'split string by delimiter' },
      { name: 'has', alias: 'contains', sig: 't t > b', desc: 'string contains substring' },
      { name: 'rgx', alias: 'regex', sig: 't t > L t', desc: 'regex match returning captures' },
      { name: 'fmt', alias: 'format', sig: 't ... > t', desc: 'format string with placeholders' },
    ],
    list: [
      { name: 'len', alias: 'length', sig: 'L _ > n', desc: 'list length' },
      { name: 'hd', alias: 'head', sig: 'L _ > _', desc: 'first element' },
      { name: 'tl', alias: 'tail', sig: 'L _ > L _', desc: 'all elements except first' },
      { name: 'rev', alias: 'reverse', sig: 'L _ > L _', desc: 'reverse a list' },
      { name: 'srt', alias: 'sort', sig: 'L _ > L _', desc: 'sort a list' },
      { name: 'srt', alias: 'sort', sig: 'fn L _ > L _', desc: 'sort by key function' },
      { name: 'slc', alias: 'slice', sig: 'L _ n n > L _', desc: 'slice (start, end)' },
      { name: 'flat', alias: 'flatten', sig: 'L L _ > L _', desc: 'flatten nested lists' },
      { name: 'unq', alias: 'unique', sig: 'L _ > L _', desc: 'remove duplicates' },
      { name: 'has', alias: 'contains', sig: 'L _ _ > b', desc: 'list contains element' },
    ],
    higher_order: [
      { name: 'map', sig: 'fn L _ > L _', desc: 'apply function to each element' },
      { name: 'flt', alias: 'filter', sig: 'fn L _ > L _', desc: 'keep elements where fn returns true' },
      { name: 'fld', alias: 'fold', sig: 'fn _ L _ > _', desc: 'reduce list to single value' },
      { name: 'grp', alias: 'group', sig: 'fn L _ > M t L _', desc: 'group elements by function result' },
    ],
    aggregation: [
      { name: 'sum', sig: 'L n > n', desc: 'sum of list' },
      { name: 'avg', alias: 'average', sig: 'L n > n', desc: 'average of list' },
    ],
    map: [
      { name: 'mmap', sig: '> M', desc: 'create empty map' },
      { name: 'mget', sig: 'M t > _', desc: 'get value by key' },
      { name: 'mset', sig: 'M t _ > M', desc: 'set key-value pair' },
      { name: 'mhas', sig: 'M t > b', desc: 'key exists' },
      { name: 'mkeys', sig: 'M > L t', desc: 'all keys' },
      { name: 'mvals', sig: 'M > L _', desc: 'all values' },
      { name: 'mdel', sig: 'M t > M', desc: 'remove key, return new map' },
    ],
    type_conversion: [
      { name: 'str', alias: 'string', sig: '_ > t', desc: 'convert to string' },
      { name: 'num', alias: 'number', sig: 't > n', desc: 'parse string to number' },
      { name: 'abs', sig: 'n > n', desc: 'absolute value' },
      { name: 'flr', alias: 'floor', sig: 'n > n', desc: 'floor' },
      { name: 'cel', alias: 'ceil', sig: 'n > n', desc: 'ceiling' },
      { name: 'rnd', alias: 'round', sig: 'n n > n', desc: 'round to N decimal places' },
    ],
    io_http: [
      { name: 'get', sig: 't > R t t', desc: 'HTTP GET', native_only: true },
      { name: '$', sig: 't > R t t', desc: 'HTTP GET sugar for get', native_only: true },
      { name: 'post', sig: 't t > R t t', desc: 'HTTP POST (url, body)', native_only: true },
      { name: 'get', sig: 't M > R t t', desc: 'HTTP GET with headers', native_only: true },
      { name: 'post', sig: 't t M > R t t', desc: 'HTTP POST with headers', native_only: true },
      { name: 'rd', alias: 'read', sig: 't > R t t', desc: 'read file' },
      { name: 'rd', alias: 'read', sig: 't t > R t t', desc: 'read file with format' },
      { name: 'wr', alias: 'write', sig: 't t > R t t', desc: 'write file (path, content)' },
      { name: 'wr', alias: 'write', sig: 't t t > R t t', desc: 'write file with format' },
      { name: 'env', sig: 't > R t t', desc: 'read environment variable' },
    ],
    json: [
      { name: 'rdb', alias: 'readbuf', sig: 't t > R _ t', desc: 'parse data (json/csv)' },
      { name: 'jpth', sig: 't t > R t t', desc: 'extract JSON path' },
      { name: 'jdmp', sig: '_ > t', desc: 'dump value as JSON string' },
      { name: 'jpar', sig: 't > R _ t', desc: 'parse JSON string' },
    ],
    output: [{ name: 'prnt', alias: 'print', sig: '_ > _', desc: 'print value and return it' }],
    time: [{ name: 'now', sig: '> n', desc: 'current Unix timestamp (seconds)' }],
  },
  features: {
    auto_unwrap: {
      suffix: '!',
      desc: 'Append ! to a Result-returning call to auto-unwrap or propagate error',
      example: 'data=rdb! r "json"',
    },
    dot_indexing: {
      desc: 'Access list elements or map fields with .',
      examples: ['xs.0', 'user.name', 'data.users.0'],
    },
    safe_navigation: {
      suffix: '.?',
      desc: 'Returns nil instead of erroring on missing keys',
      example: 'user.?email',
      example: 'user.?email',
    },
  },
  error_codes: {
    'ILO-T001': 'unknown type',
    'ILO-T002': 'parameter type missing',
    'ILO-T003': 'return type missing',
    'ILO-T004': 'type mismatch',
    'ILO-T005': 'argument count mismatch',
    'ILO-P001': 'unexpected token',
    'ILO-P002': 'unterminated string',
    'ILO-P003': 'invalid number',
    'ILO-R001': 'undefined function',
    'ILO-R002': 'undefined variable',
  },
  examples: {
    inline: 'ilo \'fn x:n>n;*x 2\' 5',
    file: 'ilo program.ilo funcname args',
    function: 'tot p:n q:n r:n>n;s=*p q;t=*s r;+s t',
  },
} as const;
